### ISSUE TITLE
SCD30 connecting

### ISSUE THREAD

**Issue by sean1985zc** [paulvha/scd30_on_raspberry#2]
Could you share your pin settings with the pi and SCD30? many thanks!

**Comment by paulvha** [comment]
it is defined in the top of the ODT document, which you can open with word or Openoffice.
SCD30	Description		           Raspberry Pi
			  			        GPIO        / PIN
VDD 	power in 3 -5 V		3V3 or 5V / 1 or 2
GND 	ground				GND         /       6
SCL 	Serial Clock			3               /        5            (*2)
SDA		Serial data			2               /        3            (*2)
RDY	data ready			Not Connected
PWM	PWM output			Not Connected
SEL		Interface Select		Not Connected

Note *2  SDA/SCL
When using soft_I2C (which is default) SDA or SCL can be set to any GPIO,

**Comment by sean1985zc** [comment]
thanks! that's really helpful
