### ISSUE TITLE
stdout delay when capturing output

### ISSUE THREAD

**Issue by lukvmil** [paulvha/scd30_on_raspberry#3]
I'm trying to integrate your program into a python application by capturing the stdout from the console. For some reason, after displaying the starting message, individual readings will not be outputted until all readings are complete. For example, the default command `./scd30` displays 10 readings in 2 second increments. The readings will not go to stdout until all 10 have completed. This is an issue as I would like to run the program continuously `./scd30 -l 0` and use the readings from there. Here is my code:

```
import subprocess, shlex
def run_command(command):
    process = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE)
    while True:
        output = process.stdout.readline()
        if output == '' and process.poll() is not None:
            break
        if output:
            print(output.strip())
    rc = process.poll()
    return rc

run_command("./scd30")
```

**Comment by paulvha** [comment]
I currently have no time to reproduce, but I did look at the code. The only difference in the output, is that that welcome message is using p_printf() and the values are displayed using printf. You could try to change in the do_output() routine the 5  'printf(' to 'p_printf(WHITE,' and see what happens.

**Comment by lukvmil** [comment]
I'll give that a try. Would I need to modify the code before running `make`?

**Comment by paulvha** [comment]
Yes.. change the printf and indicated in de do-output() and then run make.

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by lukvmil** [comment]
That seems to have worked, here is the change I made on line 404 in scd30.cpp:

`p_printf(WHITE, (char *) "CO2: %4d PPM\tHumidity: %3.2f %%RH  Temperature: %3.2f *%c  ",co2, hum,temp,t);`

**Comment by lukvmil** [comment]
I've submitted a pull request

**Comment by paulvha** [comment]
Weird.. but good to know...

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by paulvha** [comment]
I will need to change more places (in case other options were requested) and post the code today. 
Want to add your code in the appendix of the .odt file as an example how to include in Python.

**Comment by paulvha** [comment]
closed after making changes to the source to handle this
